### PR TITLE
[PLEASE READ IMPORTANT]

### PR DESCRIPTION
**Pull request by Twig6943**
title

### CODE REVIEW

**Comment by Twig6943** [comment]
Please instead of merging this PR just make a start script like [this](https://github.com/flathub/im.riot.Riot/blob/master/element.sh)

Something like 

    if  [ -c /dev/nvidia0 ]
    then
        FLAGS="$FLAGS --ozone-platform-hint=x11"

**Comment by Twig6943** [comment]
@Etaash-mathamsetty @flavioislima please have a look

**Comment by Twig6943** [comment]
Also I can no longer run the app through wayland (Something either broke on my end or in the upstream code)

Native PKG (AUR heroic-games-launcher-bin)

image

AppImage (Official)

image

Flatpak (Flathub)

image

**Comment by Twig6943** [comment]
Got it to run with the wayland backend using `--disable-gpu`

**Comment by Twig6943** [comment]
> Also I can no longer run the app through wayland (Something either broke on my end or in the upstream code)
> 
> Native PKG (AUR heroic-games-launcher-bin)
> 
> image
> 
> AppImage (Official)
> 
> image
> 
> Flatpak (Flathub)
> 
> image

I've just wiped my whole drive and reinstalled endeavouros and running "flatpak run com.heroicgameslauncher.hgl --ozone-platform-hint=wayland" gave the same result. 

Os:Endeavour
GPU:RX 580

**Comment by Etaash-mathamsetty** [comment]
> Also I can no longer run the app through wayland (Something either broke on my end or in the upstream code)
> 
> Native PKG (AUR heroic-games-launcher-bin)
> 
> image
> 
> AppImage (Official)
> 
> image
> 
> Flatpak (Flathub)
> 
> image
> 

Sounds like you need to fix your system, we haven't made a release in months

**Comment by Twig6943** [comment]
Yea this is really weird cuz this only happens with heroic (even on a fresh install)

**Pull request closed without merging**
