### PR TITLE
Wayland support & turkish description for the launcher

### PR DESCRIPTION
**Pull request by Twig6943**
title.

### CODE REVIEW

**Comment by Twig6943** [comment]
Seems to work flawlessly
https://github.com/user-attachments/assets/5029c012-c9c5-409f-bfc2-dcf56aee6852

**Comment by Twig6943** [comment]
@Etaash-mathamsetty any reason not to merge this pr?

**Comment by flavioislima** [comment]
> @flavioislima any reason not to merge this pr?

Didn't have time to test.

**Comment by flavioislima** [comment]
@Twig6943 Done. 
Thanks for the contribution!

**Pull request merged**
